### ISSUE TITLE
Add Join query string parametrs to Resource

### ISSUE THREAD

**Issue by chattago2002** [nkappler/ra-data-treeql#1]
Hello.

I'm using React-Admin with "ra-data-treeql" (I'm using "[php-crud-api](https://github.com/mevdschee/php-crud-api)").

I set
`const dataProvider = treeqlProvider('https://www.apiurl.xyz/');`
and then
`const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="sellers"list={sellerList} />
</Admin>`

With a "simple" resource from API all works fine but I need to **join** different tables (for example the partial URL in postman is sellers?join=brands&join=products).
How can I add the join parameters in Resource name? If I use
`<Resource name="sellers?join=brands&join=products"list={sellerList} />`
I receive an error.

Thanks everybody

**Comment by nkappler** [comment]
Hi, sorry for the late reply, this issue slipped through unfortunately.

As far as I am aware, react-admin doesn't support using url parameters in attributes.
I think you might want to look at https://marmelab.com/react-admin/FieldsForRelationships.html

In case this doesn't help you, you could open an issue at the react-admin repository to ask for help.
Also, if you can give me a more detailed example of what you are trying to achieve, I might be able to point you in the correct direction.

In any case, this doesn't seem to be a dataprovider related issue.

**Comment by nkappler** [comment]
Also an SQL view might be an option for you: https://www.tutorialspoint.com/sql/sql-using-views.htm

use the view to do the join and then use the view as your resource.

**Comment by chattago2002** [comment]
Sorry for my inexperience. I'm new on react-admin. After a few search I found Fields for Relationships and help me.

**Comment by nkappler** [comment]
Could you get it to work?

**Comment by chattago2002** [comment]
> Could you get it to work?

what do you mean? Using <ReferenceField> I'm able to read data from different resource/table, in relationship to a specific field from primary resource.

**Comment by nkappler** [comment]
I was wanting to know if you've tried using a join and if you did achieve what you wanted
