### ISSUE TITLE
Different filters parameters for list search

### ISSUE THREAD

**Issue by chattago2002** [nkappler/ra-data-treeql#2]
Hi.

I'm using your repo because listed on [React-Admin DataProvider List](https://marmelab.com/react-admin/DataProviderList.html).
What I was trying to understand in [this discussion](https://github.com/mevdschee/ra-data-treeql/issues/6#issue-1295815215) is to use different filter parameter for different filters fields.
How can I specify the type of filter to use in the component? Or I need to override the DataProvider getList() function?

For instance: I have this code

```
const filters = [
    <SearchInput source="name" alwaysOn />,
    <SelectInput
        alwaysOn
        source="status"
        label="status"
        choices={[
            { id: 1, status: 'On' },
            { id: 0, status: 'Off' }
        ]}
        optionText="status"
        optionValue="id"
    />,
];

export const ProductsList = () => (
    <List bulkActionButtons={false} filters={filters} perPage={100}>
        <Datagrid rowClick="edit">
            <ReferenceField source="id" reference="products">
                <TextField source="id" />
            </ReferenceField>
            <TextField source="name" label="Name" />
            <BooleanField source="status" />
        </Datagrid>
    </List>
);
```
In *filters* I need to have *name* as "cs" (contain string) and *status* as "eq" (equal).
I looked forward in [react-admin docs](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators) but no helps.
How can be made?

**Comment by nkappler** [comment]
Hi @chattago2002 

The React Admin Documentation on this topic can be found here:
https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators

This is still on my todo-list.
Fortunately, mevdschee already helped developing the required middleware: https://github.com/mevdschee/ra-data-treeql/issues/5

If you want to help with this topic, I am happy to review any pull request :)

**Comment by nkappler** [comment]
My suggestion is to support the following operators:

| operator | suffix | 
|-|-|
| equal | no suffix / default |
| not equal | `_ne` |
| greater than or equal | `_gte` |
| less then or equal | `_lte` | 
| like | `_like` |

**Comment by chattago2002** [comment]
Thanks for the reply.

I read the React Admin Documentation about [Filter Operators](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators) but is a bit complex for me at the moment (I'm neewbie with React Admin, even more with Typescript). The question was if there was something already implemented but as you wrote it's still on todo-list.
"textSearch" middleware could be a good solution at the moment but the perfect thing is to add the possibility to use filter parameters. In my case, in addition to the operators you listed could be useful the "contain string" (I suppose with "_cs" suffix).

How can I help you to do this?

**Comment by nkappler** [comment]
Contain string and `like` are semantically identical, but `like` is a sql keyword, it is concise and doesn't need to be abbreviated, thus I prefer it over `_cs` and since it is in the context of an API it probably doesn't need any further explanation.

I have some free time this evening and I will start to implement it. I'll post a status update in a few hours

**Comment by nkappler** [comment]
I've now [rewritten](https://github.com/nkappler/ra-data-treeql/commit/0b369cda67b5a884d57102a06025ae0d62af57e2) most of the dataprovider with better filter support and better typings.
I've implemented all filter operators from [php-crud-api](https://github.com/mevdschee/php-crud-api#filters)
with the suffix pattern, but I haven't tried using them yet.

Some of them require an array for the filter arguments, like `between` or `in`, so they might require some additional coding to work with react components, but the raw API calls should work.

I'm going to write some tests now, but you can review or test it if you want.
